#ifndef _ERROR_CODES_HPP_
#define _ERROR_CODES_HPP_

#define SERIAL_OPEN_ERROR       0
#define SERIAL_PARAMS_NOT_SET   1
#define SET_BASE_POS_ERROR 100

#define IDENTIFIER_TEMPLATE_LOAD_ERROR 200
#define IDENTIFIER_ERROR_LOADING_CASCADE 201

#endif
